name: DJL Demo Nightly test

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:


jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile Apache Beam
        run: cd apache-beam/ctr-prediction && mvn package
      - name: Compile Apache Kafka
        run: cd apache-kafka && ./gradlew build
      - name: Compile AWS projects
        run: |
          cd aws/aws-kinesis-video-streams && ./gradlew build && cd ..
          cd beanstalk-model-serving && ./gradlew build && cd ..
          cd emr-distributed-inference/dataprocess && ./gradlew build && cd ../../
          cd emr-distributed-inference/image-classification-gpu && ./gradlew build && cd ../../
          cd lambda-model-serving && ./gradlew build && cd ..
      - name: Compile Apache Camel
        run: cd camel-djl && mvn package
      - name: Compile Apache Flink
        run: |
          cd apache-flink/sentence_embedding && ./gradlew build && cd ..
          cd sentiment-analysis && ./gradlew build
      - name: Compile Footwear Classification
        run: cd footwear_classificaiton && ./gradlew build
      - name: Compile graalvm
        run: cd graalvm && ./mvnw package
      - name: Compile Live object detection
        run: cd live-object-detection && ./gradlew build
      - name: Compile Malicious Url Detector
        run: cd malicious-url-detector && ./gradlew build
      - name: Test Module
        run: cd module && ./gradlew test
      - name: Compile multi engine
        run: cd multi-engine && ./gradlew build
      - name: Compile Pneumonia detection
        run: cd pneumonia-detection && ./gradlew build
      - name: Compile Quarkus
        run: |
          cd quarkus/example && ./mvnw package && cd ..
          cd extension-example && ./mvnw package
      - name: Compile Apache Spark
        run: |
          cd apache-spark/image-classification && ./gradlew run && cd ..
          cd spark3.0/image-classification && ./gradlew run
      - name: Compile Web Demo
        run: |
          cd web-demo/doodle_game && ./gradlew build && cd ..
          cd interactive-console && ./gradlew build

